keys:
  - &user_aaron_entry age1dtjnc6477chq4n434t2gxf3w87ch3pww5gjzwkqavx9nqzk6zgzseek00q
  - &user_aaron_gamingpc age15lctyzps9amrf0gq2c9twt6rt0t75phfa2p4fwu6n2j0dp4x2d0qx06hwm
  - &user_aaron_mediaserver age1lthnsqvt38rm6ylhpacgm2ryhnzmhpnwc6xa2s22ntkl7fyxhggqx0qj4h
  - &server_x86-merkat-entry age1avpfrkdkw2wd9av65667syk5uvkea9574gjzqv8aswsztk9ehv9sfxhs6e
  - &server_x86-atxtwr-gamingpc age1w4yhe66tlnhwl7vkrqlqtd0f3g6z4qjv3l9eklzm27yyl900gyns4es40n
  - &server_x86-rakmnt-mediaserver age1cjk0vwkckvurf5fpltnlaa6vv0mjjgcm97xfwcatdz3ffgna6gwq9nnz7r
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
        - *user_aaron_entry
        - *user_aaron_gamingpc
        - *user_aaron_mediaserver
  - path_regex: secrets/x86-rakmnt-mediaserver/secrets.yaml$
    key_groups:
      - age:
        - *user_aaron_mediaserver
        - *server_x86-rakmnt-mediaserver
