{ lib, ... }:
{
  services.gammastep.enable = true;
  programs.wofi.enable = true;

  wayland.windowManager.hyprland = {
    enable = true;
    systemd.enable = false;
    settings = {
      "$terminal" = "wezterm";
      "$browser" = "librewolf";
      "$fileManager" = "cosmic-files";
      "$menu" = "wofi --show dmenu";
      "$mainMod" = "SUPER";

      autogenerated = 0;

      animations = {
        enabled = "yes";
        bezier = [
          "easeOutQuint,0.23,1,0.32,1"
          "easeInOutCubic,0.65,0.05,0.36,1"
          "linear,0,0,1,1"
          "almostLinear,0.5,0.5,0.75,1.0"
          "quick,0.15,0,0.1,1"
        ];
        animation = [
          "global, 1, 10, default"
          "border, 1, 5.39, easeOutQuint"
          "windows, 1, 4.79, easeOutQuint"
          "windowsIn, 1, 4.1, easeOutQuint, popin 87%"
          "windowsOut, 1, 1.49, linear, popin 87%"
          "fadeIn, 1, 1.73, almostLinear"
          "fadeOut, 1, 1.46, almostLinear"
          "fade, 1, 3.03, quick"
          "layers, 1, 3.81, easeOutQuint"
          "layersIn, 1, 4, easeOutQuint, fade"
          "layersOut, 1, 1.5, linear, fade"
          "fadeLayersIn, 1, 1.79, almostLinear"
          "fadeLayersOut, 1, 1.39, almostLinear"
          "workspaces, 1, 1.94, almostLinear, fade"
          "workspacesIn, 1, 1.21, almostLinear, fade"
          "workspacesOut, 1, 1.94, almostLinear, fade"
        ];
      };

      bind = [
        ", Print, exec, grimblast copy screen"
        "$mainMod, Q, exec, $terminal"
        "$mainMod, C, killactive"
        "$mainMod, M, exit"
        "$mainMod, E, exec, $fileManager"
        "$mainMod, V, togglefloating"
        "$mainMod, F, fullscreen, 0"
        "$mainMod, R, exec, $menu"
        "$mainMod, B, exec, $browser"
        "$mainMod, h, movefocus, l"
        "$mainMod, l, movefocus, r"
        "$mainMod, k, movefocus, u"
        "$mainMod, j, movefocus, d"
        "$mainMod SHIFT, Z, exec, hyprctl reload"
        "$mainMod SHIFT, S, exec, grimblast copy area"
        "$mainMod SHIFT, h, movewindow, l"
        "$mainMod SHIFT, l, movewindow, r"
        "$mainMod SHIFT, k, movewindow, u"
        "$mainMod SHIFT, j, movewindow, d"
        "$mainMod SHIFT, 1, movetoworkspace, 1"
        "$mainMod SHIFT, 2, movetoworkspace, 2"
        "$mainMod SHIFT, 3, movetoworkspace, 3"
        "$mainMod SHIFT, 4, movetoworkspace, 4"
        "$mainMod SHIFT, 5, movetoworkspace, 5"
        "$mainMod CTRL SHIFT, h, movetoworkspace, m-1"
        "$mainMod CTRL SHIFT, l, movetoworkspace, m+1"
        "$mainMod CTRL, h, workspace, m-1"
        "$mainMod CTRL, l, workspace, m+1"
      ];

      bindm = [
        "$mainMod, mouse:272, movewindow"
        "$mainMod, mouse:273, resizeactive"
      ];

      decoration = {
        rounding = 16;
        rounding_power = 2;
        active_opacity = 1.00;
        inactive_opacity = 0.95;
        shadow = {
          enabled = true;
          range = 4;
          render_power = 3;
        };
        blur = {
          enabled = true;
          size = 10;
          passes = 3;
          new_optimizations = true;
          ignore_opacity = true;
          noise = 0;
          brightness = 0.90;
        };
      };

      env = [
        "XCURSOR_SIZE,24"
        "HYPRCURSOR_SIZE,24"
        "XDG_SESSION_TYPE,wayland"
      ];

      exec-once = [
        "hyprpaper"
        "hypridle"
        "flatpak run com.discordapp.Discord"
        "flatpak run com.valvesoftware.Steam"
      ];

      general = {
        gaps_in = 5;
        gaps_out = 20;
        border_size = 2;
        resize_on_border = false;
        allow_tearing = true;
        layout = "dwindle";
        "col.active_border" = lib.mkForce "0x7aa2f7ff";
      };

      dwindle = {
        pseudotile = "yes";
        force_split = 2;
      };

      layerrule = [
        "blur, waybar, ignorealpha"
        "blur, wofi, ignorealpha"
      ];

      windowrule = [
        ### IMPLICIT RULES ###
        "opacity 1.0 override 0.50 override, floating:1"
        #"center, floating:1"
        "workspace 1, class:.*"

        ### TAGS ###
        "opacity 1.0 override 1.0 override 1.0 override, tag:video*"
        "float, tag:video*"
        "content video, tag:video*"
        "center, tag:video*"
        "size 1600 900, tag:video*"

        "float, tag:float-horizontal-medium*"
        "center, tag:float-horizontal-medium*"
        "size 1296 810, tag:float-horizontal-medium*"

        "float, tag:float-horizontal-big*"
        "center, tag:float-horizontal-big*"
        "size 1728 1080, tag:float-horizontal-big*"

        "float, tag:float-vertical-small*"
        "center, tag:float-vertical-small*"
        "size 540 864, tag:float-vertical-small*"

        ### CONTENT ###
        "opacity 1.0 override, content:photo"
        "opacity 1.0 override, content:video"
        "opacity 1.0 override, content:game"

        ### PORTALS ###
        "tag float-horiozontal-medium, class:Xdg-desktop-portal-gtk"
        "workspace unset, class:Xdg-desktop-portal-gtk"

        ## LIBREWOLF ##
        "tile, class:^(librewolf)$"
        "tag float-horizontal-medium, title:^(.*)(Bitwarden)(.*)$, class:^(librewolf)$" # doesn't work, 100% should work
        "tag float-horizontal-medium, title:^(Enter)(.*)$, class:^(librewolf)$"

        ## STEAM ##
        "workspace 2, class:^(steam)(.*)$"
        "workspace 2 silent, class:^(steam)$, title:^(Steam)(.*)$"
        "noinitialfocus, class:^(steam)$, title:^(Steam)$"
        "noinitialfocus, class:^(steam)$, title:^(Sign)(.*)$"
        "tag float-vertical-small, class:^(steam)$, title:^(Friends List)$"
        "tag video, class:^(steam)$, title:^(Recordings & Screenshots)$"

        ## STEAM GAMES ##
        "fullscreen, class:^(steam_app_)(.*)$"

        ## COSMIC FILES ##
        "tag float-horizontal-big, class:^.*(CosmicFiles).*$, title:^.*(COSMIC Files).*$"

        ## MPV ##
        "tag video, class:^(mpv)$"

        ## DISCORD ##
        "workspace 3 silent, class:^(discord)$"
        "noinitialfocus, class:^(discord)$"

        ## TIDAL ##
        "workspace 3, class:^(tidal-hifi)$"

        ## ZED ##
        "workspace 4, class:^.*(Zed).*$"

        ## COSMIC EDITER ##
        "tag float-horizontal-medium, class:^.*(CosmicEdit).*$"

        ## BLENDER ##
        "workspace 5, class:^(blender)$"

        ## GODOT ##
        "workspace 6, class:^.*(godotengine).*$"
        "workspace 6, initialTitle:^(Godot)$"

        ## JELLYFIN MEDIA PLAYER ##
        "tag video, class:^.*(jellyfin-media-player)$"

        ## WEZTERM ##
        "opacity 0.90 override 0.80 override 1.00 override, class:^.*(wezterm).*$"
        "opacity 0.75 override 0.25 override, class:^.*(wezterm).*$, floating:1"
        "tag float-horizontal-medium, class:^.*(wezterm).*$"
      ];

      workspace = [
        "1, monitor:DP-1, default:true, persistent:true"
        "2, monitor:DP-1"
        "3, monitor:DP-2"
        "6, monitor:DP-1"
        "f[0], rounding:false, bordersize:0, gapsout:0, persistent:false"
        "f[1], rounding:false, bordersize:0, gapsout:0, persistent:false"
      ];
    };
  };
}
