{ lib, ... }:
{
  programs = {
    wofi.enable = true;
  };

  wayland.windowManager.hyprland = {
    enable = true;
    systemd.variables = [ "--all" ];
    settings = {
      "$terminal" = "wezterm";
      "$filemanager" = "cosmic-files";
      "$menu" = "wofi --show drun";
      "$mainMod" = "SUPER";

      autogenerated = 0;

      animations = {
        enabled = "yes";
        bezier = [
          "easeOutQuint,0.23,1,0.32,1"
          "easeInOutCubic,0.65,0.05,0.36,1"
          "linear,0,0,1,1"
          "almostLinear,0.5,0.5,0.75,1.0"
          "quick,0.15,0,0.1,1"
        ];
        animation = [
          "global, 1, 10, default"
          "border, 1, 5.39, easeOutQuint"
          "windows, 1, 4.79, easeOutQuint"
          "windowsIn, 1, 4.1, easeOutQuint, popin 87%"
          "windowsOut, 1, 1.49, linear, popin 87%"
          "fadeIn, 1, 1.73, almostLinear"
          "fadeOut, 1, 1.46, almostLinear"
          "fade, 1, 3.03, quick"
          "layers, 1, 3.81, easeOutQuint"
          "layersIn, 1, 4, easeOutQuint, fade"
          "layersOut, 1, 1.5, linear, fade"
          "fadeLayersIn, 1, 1.79, almostLinear"
          "fadeLayersOut, 1, 1.39, almostLinear"
          "workspaces, 1, 1.94, almostLinear, fade"
          "workspacesIn, 1, 1.21, almostLinear, fade"
          "workspacesOut, 1, 1.94, almostLinear, fade"
        ];
      };

      bind = [
        "$mainMod, Q, exec, $terminal"
        "$mainMod, C, killactive"
        "$mainMod, M, exit"
        "$mainMod, E, exec, $fileManager"
        "$mainMod, V, togglefloating"
        "$mainMod, F, fullscreen, 0"
        "$mainMod, R, exec, $menu"
        "$mainMod, h, movefocus, l"
        "$mainMod, l, movefocus, r"
        "$mainMod, k, movefocus, u"
        "$mainMod, j, movefocus, d"
        "$mainMod SHIFT, Z, exec, hyprctl reload"
        "$mainMod SHIFT, S, exec, grimblast copy area"
        "$mainMod SHIFT, h, movewindow, l"
        "$mainMod SHIFT, l, movewindow, r"
        "$mainMod SHIFT, k, movewindow, u"
        "$mainMod SHIFT, j, movewindow, d"
        "$mainMod CTRL, h, workspace, m-1"
        "$mainMod CTRL, l, workspace, m+1"
      ];

      decoration = {
        rounding = 16;
        rounding_power = 2;
        active_opacity = 1.00;
        inactive_opacity = 0.95;
        shadow = {
          enabled = true;
          range = 4;
          render_power = 3;
        };
        blur = {
          enabled = true;
          size = 10;
          passes = 3;
          new_optimizations = true;
          ignore_opacity = true;
          noise = 0;
          brightness = 0.90;
        };
      };

      env = [
        "XCURSOR_SIZE,24"
        "HYPRCURSOR_SIZE,24"
      ];

      exec-once = [
        "waybar & hyprpaper"
      ];

      general = {
        gaps_in = 5;
        gaps_out = 20;
        border_size = 2;
        resize_on_border = false;
        allow_tearing = true;
        layout = "dwindle";
        "col.active_border" = lib.mkForce "0x7aa2f7ff";
      };

      layerrule = [
        "blur, waybar, ignorealpha"
        "blur, wofi"
      ];

      windowrule = [
        "workspace name:Steam, class:^(steam)$"
        "float, class:^(steam)$, title:(Friends List)"

        "workspace name:Discord, class:^(discord)$"

        "workspace name:Development, class:^.*(Zed).*$"

        "workspace name:Blender, class:^(blender)$"

        "float, class:^.*(pavucontrol).*$"

        "workspace name:Jellyfin, class:^.*(jellyfin-media-player).*$"

        "workspace name:Gamedev, class:^(godot)$"

        "opacity 0.90 override 0.80 override 0.95 override, class:^.*(wezterm).*$"
      ];

      workspace = [
        "f[0], rounding:false, bordersize:0, gapsout:0, persistent:false"
        "f[1], rounding:false, bordersize:0, gapsout:0, persistent:false"
        "name:General"
        "name:Steam"
        "name:Discord"
        "name:Blender"
        "name:Development"
        "name:Jellyfin"
        "name:Gamedev"
      ];
    };
  };
}
