- name: Sync /etc/nixos repo changes to all machines
  hosts: nix_machines
  become: yes # Use sudo to run the command
  tasks:
    - name: Run nix-switch -q
      command: nix-switch -q
      register: result

    - name: Display output
      debug:
        var: result.stdout
