- name: Sync /etc/nixos repo changes to all machines
  hosts: nix_servers
  become: yes
  tasks:
    - name: Start pull-updates service
      systemd:
        name: pull-updates
        state: started

    - name: Check the status of pull-updates service
      systemd:
        name: pull-updates
        state: started
      register: pull_updates_status
